name: moneva
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  flutter_dotenv: ^5.2.1
  image: ^4.3.0
  http: ^1.2.2
  provider: ^6.1.2
  flutter_svg: ^2.0.14
  path: ^1.8.1
  shared_preferences: ^2.3.3
  geolocator: ^13.0.2







dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/env/.env
